#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

mvn install:install-file -Dfile=../../app-root/repo/pdfbox-app-1.8.3.jar -DgroupId=org.apache.pdfbox -DartifactId=pdfbox -Dversion=1.8.3 -Dpackaging=jar
mvn install:install-file -Dfile=../../app-root/repo/FhtinoPdfBox-1.0.0.jar -DgroupId=it.fhtino.pdfbox.alt -DartifactId=fhpdfbox -Dversion=1.0.0 -Dpackaging=jar